
package com.acceval.integration.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2024-01-10T17:16:15.527+05:30
 * Generated source version: 3.3.2
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.integration.acceval.com/")
public class Exception_Exception extends java.lang.Exception {

    private com.acceval.integration.ws.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.acceval.integration.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.acceval.integration.ws.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.acceval.integration.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
