package com.acceval.integration.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2024-01-10T17:16:15.565+05:30
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "MasterDataWebService",
                  wsdlLocation = "file:/C:/Users/vidhiaggarwal/Documents/Projects/IOCL/code/Kpmg-iocl-dev/src/main/resources/wsdl/masterData.wsdl",
                  targetNamespace = "http://ws.integration.acceval.com/")
public class MasterDataWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.integration.acceval.com/", "MasterDataWebService");
    public final static QName MasterDataWebServicePort = new QName("http://ws.integration.acceval.com/", "MasterDataWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/vidhiaggarwal/Documents/Projects/IOCL/code/Kpmg-iocl-dev/src/main/resources/wsdl/masterData.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MasterDataWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/vidhiaggarwal/Documents/Projects/IOCL/code/Kpmg-iocl-dev/src/main/resources/wsdl/masterData.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MasterDataWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MasterDataWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MasterDataWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MasterDataWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MasterDataWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MasterDataWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MasterDataWebServicePortType
     */
    @WebEndpoint(name = "MasterDataWebServicePort")
    public MasterDataWebServicePortType getMasterDataWebServicePort() {
        return super.getPort(MasterDataWebServicePort, MasterDataWebServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MasterDataWebServicePortType
     */
    @WebEndpoint(name = "MasterDataWebServicePort")
    public MasterDataWebServicePortType getMasterDataWebServicePort(WebServiceFeature... features) {
        return super.getPort(MasterDataWebServicePort, MasterDataWebServicePortType.class, features);
    }

}
