package com.acceval.integration.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2024-01-10T17:16:15.550+05:30
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://ws.integration.acceval.com/", name = "MasterDataWebServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MasterDataWebServicePortType {

    @WebMethod
    @RequestWrapper(localName = "sendMaterial", targetNamespace = "http://ws.integration.acceval.com/", className = "com.acceval.integration.ws.SendMaterial")
    @ResponseWrapper(localName = "sendMaterialResponse", targetNamespace = "http://ws.integration.acceval.com/", className = "com.acceval.integration.ws.SendMaterialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.acceval.integration.ws.MasterDataStatusMessage sendMaterial(

        @WebParam(name = "arg0", targetNamespace = "http://ws.integration.acceval.com/")
        com.acceval.integration.ws.MasterDataMaterialInMessage arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendCustomer", targetNamespace = "http://ws.integration.acceval.com/", className = "com.acceval.integration.ws.SendCustomer")
    @ResponseWrapper(localName = "sendCustomerResponse", targetNamespace = "http://ws.integration.acceval.com/", className = "com.acceval.integration.ws.SendCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.acceval.integration.ws.MasterDataStatusMessage sendCustomer(

        @WebParam(name = "arg0", targetNamespace = "http://ws.integration.acceval.com/")
        com.acceval.integration.ws.MasterDataCustomerInMessage arg0
    ) throws Exception_Exception;
}
